# Generated by Django 5.2.13 on 2026-04-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=4096, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='folder-kanban', max_length=64)),
                ('is_imported', models.BooleanField(default=False, help_text='True if added via import path rather than root scan.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_root', models.CharField(default='/home/sam/projects/', help_text='Directory whose immediate subdirectories are scanned as projects.', max_length=4096)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
